server:
  port: 8086

password-generator:
  pattern: Aaaaaaaaaa00000

#Logging
logging:
  level:
    root: info
  file:
    name: logs/serv.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=panda
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  properties:
    hibernate:
      default_schema: panda
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgrespw
    default-schema: panda

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

instance:
  status-page-url-path: actuator/info
  health-check-url-path: actuator/health
  instance-id: "${spring.application.name}:${random.uuid}"
