server:
  port: 28086

spring:
  application:
    name: api-panda-service
  profiles:
    active: dev
  messages:
    always-use-message-format: false
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: true

#Open-api
springdoc:
  api-docs:
    path: /panda-docs

#Prometheus
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,loggers
  metrics:
    enable:
      jvm: true